git:
  depth: 10
notifications:
  email: false

language: cpp
compiler: clangss
os:
  - linux
  - osx
env:
  - TARGET_ARCH=x64
osx_image: xcode7

matrix:
  include:
    - os: lin
      env: TARGET_ARCH=arm
    - os: linux
      env: TARGET_ARCH=ia32
  allow_failures:
    - os: osx

script: './script/cibuild'

branches:
  only:
    - master
